### ISSUE TITLE
Build error on 10.8 x86_64 with clang: `ex003.cpp: error: use of undeclared identifier 'EXIT_SUCCESS'`

### ISSUE THREAD

**Issue by barracuda156** [d99kris/heapusage#21]
**Description**:

For some reason this fails:
```
/opt/local/var/macports/build/_opt_MountainLionPorts_devel_heapusage/heapusage/work/heapusage-867461cdb82313be185c918a7305e4b9974975b0/tests/ex003.cpp:58:12: error: use of undeclared identifier 'EXIT_SUCCESS'
    return EXIT_SUCCESS;
           ^
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_MountainLionPorts_devel_heapusage/heapusage/work/build'
1 error generated.
make[2]: *** [CMakeFiles/ex003.dir/tests/ex003.cpp.o] Error 1
```

**How to reproduce it**:

Run the build on 10.8.5 with Apple clang from 867461cdb82313be185c918a7305e4b9974975b0

**Environment**:
- Version: 10.8.5
- OS / distro: macOS
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.8.5
BuildVersion:	12F2560
```
